/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VIEW;
import DAO.D_CUSTOMERS;
import Model.Model_Customers;
import com.itextpdf.kernel.colors.Color;
import com.itextpdf.kernel.colors.DeviceRgb;
import com.itextpdf.kernel.pdf.PdfDocument;
import com.itextpdf.kernel.pdf.PdfWriter;
import com.itextpdf.layout.Document;
import com.itextpdf.layout.element.Cell;
import com.itextpdf.layout.element.Paragraph;
import com.itextpdf.layout.element.Table;
import java.io.FileNotFoundException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author BIDERI ALEC
 */
public class CUSTOMER_DASHBOARD extends javax.swing.JFrame {

    /**
     * Creates new form CUSTOMER_DASHBOARD
     */
    private String email ;

    public CUSTOMER_DASHBOARD(String email) {
        this.email = email;
        initComponents();
        display_customer_info();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        home_btn = new javax.swing.JLabel();
        logout_btn = new javax.swing.JLabel();
        welcome = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        full_name = new javax.swing.JLabel();
        loan_amount = new javax.swing.JLabel();
        rate = new javax.swing.JLabel();
        payback = new javax.swing.JLabel();
        monthly_pay = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        reprort_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        home_btn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        home_btn.setText("Home");

        logout_btn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        logout_btn.setText("Logout");
        logout_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logout_btnMouseClicked(evt);
            }
        });

        welcome.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        welcome.setText("Welcome Back:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(373, 373, 373)
                .addComponent(home_btn)
                .addGap(84, 84, 84)
                .addComponent(logout_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(548, Short.MAX_VALUE)
                .addComponent(welcome, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(home_btn)
                    .addComponent(logout_btn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 153, Short.MAX_VALUE)
                .addComponent(welcome)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(102, 255, 204));

        full_name.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        full_name.setText("Full Name : ");

        loan_amount.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        loan_amount.setText("Loan Amount:");

        rate.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        rate.setText("Interest Rate:");

        payback.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        payback.setText("Payback Amount :");

        monthly_pay.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        monthly_pay.setText("Monthly Payments:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(full_name)
                    .addComponent(loan_amount)
                    .addComponent(rate)
                    .addComponent(payback)
                    .addComponent(monthly_pay))
                .addContainerGap(281, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(full_name)
                .addGap(74, 74, 74)
                .addComponent(loan_amount)
                .addGap(74, 74, 74)
                .addComponent(rate)
                .addGap(74, 74, 74)
                .addComponent(payback)
                .addGap(74, 74, 74)
                .addComponent(monthly_pay)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/speedy_big.png"))); // NOI18N

        reprort_btn.setBackground(new java.awt.Color(102, 255, 204));
        reprort_btn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        reprort_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/185102_receipt_shopping_icon.png"))); // NOI18N
        reprort_btn.setText("Bill");
        reprort_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reprort_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(reprort_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(117, 117, 117))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(reprort_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(134, 134, 134))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void logout_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logout_btnMouseClicked
        this.dispose();
        new LOGIN_GUI().show();
    }//GEN-LAST:event_logout_btnMouseClicked

    private void reprort_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reprort_btnActionPerformed
          try {
            String fileName = "Loan_report_" + System.currentTimeMillis() + ".pdf"; // Unique filename based on timestamp
            PdfDocument pdfDoc = new PdfDocument(new PdfWriter(fileName));
            Document document = new Document(pdfDoc);
            Color blueColor = new DeviceRgb(0, 0, 255);
            // Title of the report
            document.add(new Paragraph("Loan Report").setFontColor(blueColor).setBold().setFontSize(20f));
            document.add(new Paragraph("_________________"));
            document.add(new Paragraph());

            // Table header
            Table table = new Table(new float[]{1, 3, 3, 5, 2}).useAllAvailableWidth();
            table.addCell(new Cell().add(new Paragraph("Full names")));
            table.addCell(new Cell().add(new Paragraph("Loan Amount")));
            table.addCell(new Cell().add(new Paragraph("Interest Rate")));
            table.addCell(new Cell().add(new Paragraph("Payback")));
            table.addCell(new Cell().add(new Paragraph("Monthly payment")));

            // Populate table with customer data
              D_CUSTOMERS d_customer = new D_CUSTOMERS();
              Model_Customers customer = d_customer.selectCustomerInfoByEmail(email);

                table.addCell(new Cell().add(new Paragraph(customer.getName())));
                table.addCell(new Cell().add(new Paragraph(String.valueOf(customer.getLoan()))));
                table.addCell(new Cell().add(new Paragraph(String.valueOf(customer.getInterest_rate()))));
                table.addCell(new Cell().add(new Paragraph(String.valueOf(customer.getPayback()))));
                table.addCell(new Cell().add(new Paragraph(String.valueOf(customer.getPayback_month()))));
            

            // Add the table to the document
            document.add(table);

            document.close();
            JOptionPane.showMessageDialog(this, "Report generated successfully!");
        } catch (FileNotFoundException ex) {
            Logger.getLogger(LOAN_REG_GUI.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_reprort_btnActionPerformed

     private void display_customer_info(){
         
         D_CUSTOMERS d_customer = new D_CUSTOMERS();
         Model_Customers customer = d_customer.selectCustomerInfoByEmail(email);
         
         full_name.setText("Full Name : " + customer.getName());
         welcome.setText("Welcome Back: " + customer.getName());
         rate.setText("Interest rate : "+String.valueOf(customer.getInterest_rate()) + "%");
         payback.setText("Payback: "+ String.valueOf(customer.getPayback())+ " RWF");
         monthly_pay.setText("Monthly Payment: " +String.valueOf(customer.getPayback_month())+" RWF");
         loan_amount.setText("Loan Amount : " + String.valueOf(customer.getLoan()) + " RWF");
         
         
     }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CUSTOMER_DASHBOARD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CUSTOMER_DASHBOARD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CUSTOMER_DASHBOARD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CUSTOMER_DASHBOARD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        String email = "username";
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CUSTOMER_DASHBOARD(email).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel full_name;
    private javax.swing.JLabel home_btn;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel loan_amount;
    private javax.swing.JLabel logout_btn;
    private javax.swing.JLabel monthly_pay;
    private javax.swing.JLabel payback;
    private javax.swing.JLabel rate;
    private javax.swing.JButton reprort_btn;
    private javax.swing.JLabel welcome;
    // End of variables declaration//GEN-END:variables
}
